### ISSUE TITLE
How can i remove 0.00 default value in the currency mask?

### ISSUE THREAD

**Issue by bearnithi** [cesarrew/ng2-currency-mask#129]
I have a need to remove 0.00 as a default value in the input box. 
I want to show only $ as a default value. Is there anyway to achieve it. Please help me to solve this issue.

**Comment by wrm192** [comment]
In the form builder group you can set the initial value to null, if you are using that approach.

**Comment by guillep2k** [comment]
Hi, @bearnithi. A [fork of this project](https://github.com/christopheelkhoury/ng2-currency-mask/issues/new) has been created due to the original developer's current unavailability, in the hope that the project would advance more quickly. If your question was not answered, would you like to re-open an issue there?
